#+STARTUP:showall

* NEWS
** Version 3.9.9-pre

*** Get rid of popup.el dependency
*** helm-completion-styles-alist accepts commands for completion-in-region
*** Minibuffer-contents change color in HFF when updating
This is controlled by =helm-ff-dim-prompt-on-update= user variable.

*** Now new file and dir have a dummy source in HFF, same for completing-read's
and read-file-name.

*** helm-info-at-point shows index of current page in addition of default

So it can safely be used as a replacement of "i" in Info.

*** Add affixation function for eww (emacs-30 only)
*** Allow toggling auto update in helm-top with a prefix arg
*** Do not use `dired-create-destination-dirs` mechanism for directory creation
as it is not working in some cases (e.g. symlinks).
*** Fix persistent action in helm mark-ring when follow mode is on
*** Fix Imenu preselection when point is on a name with special chars
*** Provide a new progress bar for rsync with a svg widget 
Needs svg-lib package but it is not mandatory.

** Version 3.9.8

*** New helm-finder command
*** Make `completions-detailed` working with 'emacs' helm-completion-style
It was already working but was really slow and was not supporting
`helm-completing-read-command-categories` mechanism which provide
`completions-detailed` in much more places than Emacs vanilla.
*** Helm-goto-line save position even when using persistent actions
*** helm-info is now colorized
*** Displaying thumnails is now slighly faster
*** Add a new mode to edit bookmark annotations
When viewing an annotation you had to kill the buffer, restart
helm-bookmarks, and run the edit annotation action, now you can edit
directly from the view buffer.
*** It is now possible to rename marked bookmarks
*** New compress/uncompress/compress-to action in helm-find-files
All actions are asynchronous except the persistent ones.
*** Allow toggling while-no-input for easier edebugging
Use the new `helm-update-edebug` variable to enable this.
*** And various bug fixes as always

** Version 3.9.7

*** Fix package-requires in helm.el

** Version 3.9.6

*** Fix bug with helm-mm-exact-search (bug#2616)
*** Improve locate library fns
*** Fix a old bug with candidate transformer
candidate-transformer functions should behave the same in in-buffer
and sync source: transforming all candidates.
*** Fix kmacro for Emacs-29+
*** Various minor bug fixes

** Version 3.9.5

*** Add compatibility with Emacs-28< for helm-packages

Tested with emacs-27.

*** Add new action package-isolate for helm-packages

Allow launching a new Emacs with only package(s).

*** Packages list can be refreshed with C-c C-u

BTW there is no more option to update from actions with prefix arg.

*** Add more affixations fns for completing-read

Themes, colors etc...

*** Add new var helm-compleions-detailed for emacs-27

This allow using completions-detailed in Emacs-27 with various
describe-* functions.

*** Helm-occur now doesn't hang when trying to match empty lines

With "^$".

*** Highlight matches in M-x highlight only commands

I.e. Items in short documentation are not highlighted.

** Version 3.9.4

*** Add two new alists to allow extending completions-detailed

This allows providing detailed completions in more places, see
`helm-completing-read-extra-metadata` and
`helm-completing-read-command-categories`.
They are not provided as user variables as it may be tricky to provide
the corresponding affixations functions.
As of now we have detailed completions in
describe-function/variable/symbol/command/package,
find-function/variable, switch-to-buffer,
customize-variable/group, package-(vc)install, package-vc-checkout.

*** New helm packages manager

The old helm-elisp-package has been replaced by helm-packages.
The old one was too slow, taking lot of memory and even crashing Emacs
especially with last Emacs-29.

** Version 3.9.3

*** Ensure to use affixation functions provided by caller in helm-mode

** Version 3.9.2

*** New progress bar for Rsync action from helm-find-files
*** Describe-* commands with completions-detailed are now fast
*** Use Wfnames package as dependency to replace Wdired

** Version 3.9.1

*** helm-config file has been removed

Therefore (require 'helm-config) will return an error, don't use this
anymore. If installing from source use instead (require 'helm-autoloads), otherwise from a package install, the autoloads file
will be automatically loaded.


*** Allow using helm-completion-styles-alist by command

*** New mode for editing large vars

Will be used automatically when using the set variable action from
helm-apropos.

*** Improve all-the-icons in many places
