@startuml
skinparam classFontStyle bold
skinparam classBackGroundColor #fbfb77
skinparam TitleFontStyle bold
skinparam TitleFontSize 24
title Classes in library 'Helm'\n\n
class "helm-locate-source" {
}
"helm-source-async" <|-- "helm-locate-source"
"helm-locate-override-inheritor" <|-- "helm-locate-source"
class "helm-locate-override-inheritor" {
}
"helm-type-file" <|-- "helm-locate-override-inheritor"
class "helm-file-cache" {
}
"helm-source-in-buffer" <|-- "helm-file-cache"
"helm-type-file" <|-- "helm-file-cache"
class "helm-browse-project-source" {
	Class to define a source in
	`helm-browse-project' handling
	non
	==
}
"helm-source-in-buffer" <|-- "helm-browse-project-source"
"helm-browse-project-override-inheritor" <|-- "helm-browse-project-source"
class "helm-browse-project-override-inheritor" {
}
"helm-type-file" <|-- "helm-browse-project-override-inheritor"
class "helm-fd-class" {
}
"helm-source-async" <|-- "helm-fd-class"
class "helm-absolute-time-timers-class" {
}
"helm-source-sync" <|-- "helm-absolute-time-timers-class"
"helm-type-timers" <|-- "helm-absolute-time-timers-class"
class "helm-M-x-class" {
}
"helm-source-sync" <|-- "helm-M-x-class"
"helm-type-command" <|-- "helm-M-x-class"
class "helm-source-buffers" {
}
"helm-source-sync" <|-- "helm-source-buffers"
"helm-type-buffer" <|-- "helm-source-buffers"
class "helm-bookmark-find-files-class" {
}
"helm-source-filtered-bookmarks" <|-- "helm-bookmark-find-files-class"
"helm-bookmark-override-inheritor" <|-- "helm-bookmark-find-files-class"
class "helm-bookmark-override-inheritor" {
}
"helm-source" <|-- "helm-bookmark-override-inheritor"
class "helm-source-filtered-bookmarks" {
}
"helm-source-in-buffer" <|-- "helm-source-filtered-bookmarks"
"helm-type-bookmark" <|-- "helm-source-filtered-bookmarks"
class "helm-source-basic-bookmarks" {
}
"helm-source-in-buffer" <|-- "helm-source-basic-bookmarks"
"helm-type-bookmark" <|-- "helm-source-basic-bookmarks"
class "helm-mac-spotlight-source" {
}
"helm-source-async" <|-- "helm-mac-spotlight-source"
"helm-type-file" <|-- "helm-mac-spotlight-source"
class "helm-source-session-class" {
}
"helm-source-sync" <|-- "helm-source-session-class"
class "helm-files-dired-source" {
}
"helm-source-sync" <|-- "helm-files-dired-source"
"helm-type-file" <|-- "helm-files-dired-source"
class "helm-type-timers" {
	A class to define helm type
	timers.
	==
}
"helm-source" <|-- "helm-type-timers"
class "helm-type-command" {
	A class to define helm type
	command.
	==
}
"helm-source" <|-- "helm-type-command"
class "helm-type-buffer" {
	A class to define type buffer.
	==
}
"helm-source" <|-- "helm-type-buffer"
class "helm-type-bookmark" {
	A class to define type
	bookmarks.
	==
}
"helm-source" <|-- "helm-type-bookmark"
class "helm-type-file" {
	A class to define helm type
	file.
	==
}
"helm-source" <|-- "helm-type-file"
class "helm-source-in-file" {
	The contents of the FILE will
	be used as candidates in
	buffer.
	==
}
"helm-source-in-buffer" <|-- "helm-source-in-file"
class "helm-source-dummy" {
}
"helm-source" <|-- "helm-source-dummy"
class "helm-source-in-buffer" {
	Use this source to make helm
	sources storing candidates
	inside a buffer.
	==
}
"helm-source" <|-- "helm-source-in-buffer"
class "helm-source-async" {
	Use this class to define a
	helm source calling an
	external process.
	==
}
"helm-source" <|-- "helm-source-async"
class "helm-source-sync" {
	Use this class to make helm
	sources using a list of
	candidates.
	==
}
"helm-source" <|-- "helm-source-sync"
class "helm-source" {
	Main interface to define helm
	sources.
	==
}
package "Other classes similar to 'helm-fd-class'" {
	"helm-fd-class" -down[hidden]-> "helm-grep-class"
	"helm-grep-class" -down[hidden]-> "helm-grep-ag-class"
	"helm-grep-ag-class" -down[hidden]-> "helm-gid-source"
}
package "Other classes similar to 'helm-absolute-time-timers-class'" {
	"helm-absolute-time-timers-class" -down[hidden]-> "helm-idle-time-timers-class"
}
package "Other classes similar to 'helm-source-session-class'" {
	"helm-source-session-class" -down[hidden]-> "helm-epa"
	"helm-epa" -down[hidden]-> "helm-esh-source"
	"helm-esh-source" -down[hidden]-> "helm-eshell-history-source"
	"helm-eshell-history-source" -down[hidden]-> "helm-source-ffiles"
	"helm-source-ffiles" -down[hidden]-> "helm-imenu-source"
}
package "Other classes similar to 'helm-files-dired-source'" {
	"helm-files-dired-source" -down[hidden]-> "helm-recentf-source"
	"helm-recentf-source" -down[hidden]-> "helm-files-in-current-dir-source"
}
package "Other classes similar to 'helm-source-in-file'" {
	"helm-source-in-file" -down[hidden]-> "helm-list-el-package-source"
	"helm-list-el-package-source" -down[hidden]-> "helm-info-source"
	"helm-info-source" -down[hidden]-> "helm-locate-subdirs-source"
	"helm-locate-subdirs-source" -down[hidden]-> "helm-moccur-class"
	"helm-moccur-class" -down[hidden]-> "helm-semantic-source"
}
package "Other classes similar to 'helm-source-dummy'" {
	"helm-source-dummy" -down[hidden]-> "helm-type-function"
}
@enduml
