@startuml
skinparam classFontStyle bold
skinparam captionFontStyle bold
title **Parents and Children of**\n**'helm-source-in-file'**\n\n
"helm-source-in-buffer" <|-- "helm-source-in-file"
class "helm-source-in-buffer"
"helm-source" <|-- "helm-source-in-buffer"
class "helm-source"
class "helm-source-in-file" {
	The contents of the FILE will
	be used as candidates in
	buffer.
	==
	__ some interesting slots __
	init
	candidates-file
	get-line
}
note right of "helm-source-in-file"
	**helm-source-in-file**:
	The contents of the FILE will
	be used as candidates in
	buffer.
end note
@enduml
