@startuml
skinparam classFontStyle bold
skinparam captionFontStyle bold
title **Parents and Children of**\n**'helm-mac-spotlight-source'**\n\n
"helm-source-async" <|-- "helm-mac-spotlight-source"
"helm-type-file" <|-- "helm-mac-spotlight-source"
class "helm-source-async"
"helm-source" <|-- "helm-source-async"
class "helm-source"
class "helm-type-file"
"helm-source" <|-- "helm-type-file"
class "helm-source"
class "helm-mac-spotlight-source" {
	__ some interesting slots __
	candidates-process
	multimatch
	requires-pattern
}
note right of "helm-mac-spotlight-source"
	**helm-mac-spotlight-source**
end note
@enduml
