@startuml
skinparam classFontStyle bold
skinparam captionFontStyle bold
title **Parents and Children of**\n**'helm-info-source'**\n\n
"helm-source-in-buffer" <|-- "helm-info-source"
class "helm-source-in-buffer"
"helm-source" <|-- "helm-source-in-buffer"
class "helm-source"
class "helm-info-source" {
	__ some interesting slots __
	init
	action
	display-to-real
	get-line
	info-file
}
note right of "helm-info-source"
	**helm-info-source**
end note
@enduml
