@startuml
skinparam classFontStyle bold
skinparam captionFontStyle bold
title **Parents and Children of**\n**'helm-bookmark-find-files-class'**\n\n
"helm-source-filtered-bookmarks" <|-- "helm-bookmark-find-files-class"
"helm-bookmark-override-inheritor" <|-- "helm-bookmark-find-files-class"
class "helm-source-filtered-bookmarks"
"helm-source-in-buffer" <|-- "helm-source-filtered-bookmarks"
"helm-type-bookmark" <|-- "helm-source-filtered-bookmarks"
class "helm-source-in-buffer"
"helm-source" <|-- "helm-source-in-buffer"
class "helm-source"
class "helm-type-bookmark"
"helm-source" <|-- "helm-type-bookmark"
class "helm-source"
class "helm-bookmark-override-inheritor"
"helm-source" <|-- "helm-bookmark-override-inheritor"
class "helm-source"
class "helm-bookmark-find-files-class" {
	__ some interesting slots __
	init
	candidates
	data
	filtered-candidate-transformer
	get-line
	match
	migemo
	search
	search-strict
	volatile
}
note right of "helm-bookmark-find-files-class"
	**helm-bookmark-find-files-class**
end note
@enduml
