@startuml
skinparam classFontStyle bold
skinparam captionFontStyle bold
title **Parents and Children of**\n**'helm-recentf-source'**\n\n
"helm-source-sync" <|-- "helm-recentf-source"
"helm-type-file" <|-- "helm-recentf-source"
class "helm-source-sync"
"helm-source" <|-- "helm-source-sync"
class "helm-source"
class "helm-type-file"
"helm-source" <|-- "helm-type-file"
class "helm-source"
class "helm-recentf-source" {
	__ some interesting slots __
	init
	candidates
	match-dynamic
	match-part
	match-strict
	migemo
	pattern-transformer
	persistent-action
}
note right of "helm-recentf-source"
	**helm-recentf-source**
end note
@enduml
