#+title: How to report Helm Bugs
# #+subtitle:  Release {{{version}}}
# #+author:    The Org Mode Developers
# #+date:      {{{modification-time}}}
#+language:  en

# #+texinfo: @insertcopying

** Confirming bugs

To confirm that a bug is, in fact, a Helm problem, it is important to
/replicate the behavior with a minimal Emacs configuration/. This
precludes the possibility that the bug is caused by factors outside of
Helm.

The easiest and recommended way to do so is through the
=emacs-helm.sh= script.

*** =emacs-helm.sh=

If your system supports it, you should run the =emacs-helm.sh= script
to start an Emacs instance with minimal, Helm-specific configuration.

This is useful for debugging, and easier than starting Emacs with
=emacs -Q= and configuring Helm from scratch.

If Helm is installed via MELPA, the =emacs-helm.sh= script should be
located at =~/.emacs.d/elpa/helm-<version>/emacs-helm.sh=.

Of course you have to cd to your helm directory and run the script
from there, an alternative is symlinking it to somewhere in your
=PATH= e.g. "~/bin" (See note at bottom for those that have installed
from source with =make=).

You can use the -h argument for help:

    : $ helm -h
    : Usage: helm [-P} Emacs path [-h} help [--] EMACS ARGS

If your emacs binary is not in a standard place i.e. "emacs", you can
specify the path with "-P".

~Note~: If you have installed Helm from Git and used =make && sudo
make install= you can run directly =helm= at command line from any
place i.e. no need to cd to helm directory.

*** =emacs -Q=

If you cannot run the =emacs-helm.sh= script, be sure to reproduce the
problem with =emacs -Q=, then installing Helm as described in the
Install section.

** Reporting bugs

To report a bug, [[https://github.com/emacs-helm/helm/issues][open an
issue]]. Be sure that you've confirmed the bug as described in the
previous section, and include relevant information for the maintainer
to identify the bug.

*** Version info

When reporting bugs, it is important to include the Helm version
number, which can be found in the
[[https://github.com/emacs-helm/helm/blob/master/helm-pkg.el][helm-pkg.el]]
file.

* Export Setup                                                          :noexport:

#+setupfile: doc-setup.org

#+export_file_name: helm-bugs.texi

#+texinfo_dir_category: Emacs editing modes
#+texinfo_dir_title: Reporting Helm Bugs: (report-helm-bugs.org)
#+texinfo_dir_desc: Report Helm Bugs

* Footnotes
