@startuml
skinparam classFontStyle bold
skinparam captionFontStyle bold
title **Parents and Children of**\n**'helm-grep-class'**\n\n
"helm-source-async" <|-- "helm-grep-class"
class "helm-source-async"
"helm-source" <|-- "helm-source-async"
class "helm-source"
class "helm-grep-class" {
	__ some interesting slots __
	action
	after-init-hook
	backend
	before-init-hook
	candidate-number-limit
	candidates-process
	filtered-candidate-transformer
	group
	help-message
	history
	keymap
	nohighlight
	nomark
	pcre
	persistent-action
	persistent-help
	requires-pattern
}
note right of "helm-grep-class"
	**helm-grep-class**
end note
@enduml
