@startuml
skinparam classFontStyle bold
skinparam captionFontStyle bold
title **Parents and Children of**\n**'helm-type-bookmark'**\n\n
"helm-source" <|-- "helm-type-bookmark"
class "helm-source"
class "helm-type-bookmark" {
	A class to define type
	bookmarks.
	==
	__ some interesting slots __
}
note right of "helm-type-bookmark"
	**helm-type-bookmark**:
	A class to define type
	bookmarks.
end note
"helm-type-bookmark" <|-- "helm-source-filtered-bookmarks"
"helm-type-bookmark" <|-- "helm-source-basic-bookmarks"
@enduml
