@startuml
skinparam classFontStyle bold
skinparam captionFontStyle bold
title **Parents and Children of**\n**'helm-type-command'**\n\n
"helm-source" <|-- "helm-type-command"
class "helm-source"
class "helm-type-command" {
	A class to define helm type
	command.
	==
	__ some interesting slots __
}
note right of "helm-type-command"
	**helm-type-command**:
	A class to define helm type
	command.
end note
"helm-type-command" <|-- "helm-M-x-class"
@enduml
