@startuml
skinparam classFontStyle bold
skinparam captionFontStyle bold
title **Parents and Children of**\n**'helm-list-el-package-source'**\n\n
"helm-source-in-buffer" <|-- "helm-list-el-package-source"
class "helm-source-in-buffer"
"helm-source" <|-- "helm-source-in-buffer"
class "helm-source"
class "helm-list-el-package-source" {
	__ some interesting slots __
	init
	action
	action-transformer
	candidate-number-limit
	filtered-candidate-transformer
	get-line
	group
	help-message
	keymap
	update
}
note right of "helm-list-el-package-source"
	**helm-list-el-package-source**
end note
@enduml
