@startuml
skinparam classFontStyle bold
skinparam captionFontStyle bold
title **Parents and Children of**\n**'helm-browse-project-source'**\n\n
"helm-source-in-buffer" <|-- "helm-browse-project-source"
"helm-browse-project-override-inheritor" <|-- "helm-browse-project-source"
class "helm-source-in-buffer"
"helm-source" <|-- "helm-source-in-buffer"
class "helm-source"
class "helm-browse-project-override-inheritor"
"helm-type-file" <|-- "helm-browse-project-override-inheritor"
class "helm-type-file"
"helm-source" <|-- "helm-type-file"
class "helm-source"
class "helm-browse-project-source" {
	Class to define a source in
	`helm-browse-project' handling
	non
	==
	__ some interesting slots __
	init
	candidates
	data
	filter-one-by-one
	get-line
	match
	match-part
	migemo
	root-dir
	search
	search-strict
	volatile
}
note right of "helm-browse-project-source"
	**helm-browse-project-source**:
	Class to define a source in
	`helm-browse-project' handling
	non
end note
@enduml
