@startuml
skinparam classFontStyle bold
skinparam captionFontStyle bold
title **Parents and Children of**\n**'helm-M-x-class'**\n\n
"helm-source-sync" <|-- "helm-M-x-class"
"helm-type-command" <|-- "helm-M-x-class"
class "helm-source-sync"
"helm-source" <|-- "helm-source-sync"
class "helm-source"
class "helm-type-command"
"helm-source" <|-- "helm-type-command"
class "helm-source"
class "helm-M-x-class" {
	__ some interesting slots __
	candidates
	filtered-candidate-transformer
	help-message
	keymap
	match-dynamic
	match-strict
	migemo
	must-match
	nomark
	persistent-help
}
note right of "helm-M-x-class"
	**helm-M-x-class**
end note
@enduml
