@startuml
skinparam classFontStyle bold
skinparam captionFontStyle bold
title **Parents and Children of**\n**'helm-eshell-history-source'**\n\n
"helm-source-sync" <|-- "helm-eshell-history-source"
class "helm-source-sync"
"helm-source" <|-- "helm-source-sync"
class "helm-source"
class "helm-eshell-history-source" {
	Helm class to define source
	for Eshell history.
	==
	__ some interesting slots __
	init
	action
	candidate-number-limit
	candidates
	keymap
	multiline
	nomark
}
note right of "helm-eshell-history-source"
	**helm-eshell-history-source**:
	Helm class to define source
	for Eshell history.
end note
@enduml
