@startuml
skinparam classFontStyle bold
skinparam captionFontStyle bold
title **Parents and Children of**\n**'helm-type-buffer'**\n\n
"helm-source" <|-- "helm-type-buffer"
class "helm-source"
class "helm-type-buffer" {
	A class to define type buffer.
	==
	__ some interesting slots __
}
note right of "helm-type-buffer"
	**helm-type-buffer**:
	A class to define type buffer.
end note
"helm-type-buffer" <|-- "helm-source-buffers"
@enduml
