@startuml
skinparam classFontStyle bold
skinparam captionFontStyle bold
title **Parents and Children of**\n**'helm-type-timers'**\n\n
"helm-source" <|-- "helm-type-timers"
class "helm-source"
class "helm-type-timers" {
	A class to define helm type
	timers.
	==
	__ some interesting slots __
}
note right of "helm-type-timers"
	**helm-type-timers**:
	A class to define helm type
	timers.
end note
"helm-type-timers" <|-- "helm-idle-time-timers-class"
"helm-type-timers" <|-- "helm-absolute-time-timers-class"
@enduml
