@startuml
skinparam classFontStyle bold
skinparam captionFontStyle bold
title **Parents and Children of**\n**'helm-esh-source'**\n\n
"helm-source-sync" <|-- "helm-esh-source"
class "helm-source-sync"
"helm-source" <|-- "helm-source-sync"
class "helm-source"
class "helm-esh-source" {
	Helm class to define source
	for Eshell completion.
	==
	__ some interesting slots __
	init
	action
	candidates
	filtered-candidate-transformer
	nohighlight
	persistent-action
}
note right of "helm-esh-source"
	**helm-esh-source**:
	Helm class to define source
	for Eshell completion.
end note
@enduml
