@startuml
skinparam classFontStyle bold
skinparam captionFontStyle bold
title **Parents and Children of**\n**'helm-semantic-source'**\n\n
"helm-source-in-buffer" <|-- "helm-semantic-source"
class "helm-source-in-buffer"
"helm-source" <|-- "helm-source-in-buffer"
class "helm-source"
class "helm-semantic-source" {
	__ some interesting slots __
	init
	action
	get-line
	help-message
	keymap
	persistent-action
	persistent-help
}
note right of "helm-semantic-source"
	**helm-semantic-source**
end note
@enduml
