@startuml
skinparam classFontStyle bold
skinparam captionFontStyle bold
title **Parents and Children of**\n**'helm-bookmark-override-inheritor'**\n\n
"helm-source" <|-- "helm-bookmark-override-inheritor"
class "helm-source"
class "helm-bookmark-override-inheritor" {
	__ some interesting slots __
}
note right of "helm-bookmark-override-inheritor"
	**helm-bookmark-override-inheritor**
end note
"helm-bookmark-override-inheritor" <|-- "helm-bookmark-find-files-class"
@enduml
