@startuml
skinparam classFontStyle bold
skinparam captionFontStyle bold
title **Parents and Children of**\n**'helm-locate-source'**\n\n
"helm-source-async" <|-- "helm-locate-source"
"helm-locate-override-inheritor" <|-- "helm-locate-source"
class "helm-source-async"
"helm-source" <|-- "helm-source-async"
class "helm-source"
class "helm-locate-override-inheritor"
"helm-type-file" <|-- "helm-locate-override-inheritor"
class "helm-type-file"
"helm-source" <|-- "helm-type-file"
class "helm-source"
class "helm-locate-source" {
	__ some interesting slots __
	init
	candidate-number-limit
	candidates-process
	group
	history
	multimatch
	persistent-action
	redisplay
	requires-pattern
}
note right of "helm-locate-source"
	**helm-locate-source**
end note
@enduml
