@startuml
skinparam classFontStyle bold
skinparam captionFontStyle bold
title **Parents and Children of**\n**'helm-files-dired-source'**\n\n
"helm-source-sync" <|-- "helm-files-dired-source"
"helm-type-file" <|-- "helm-files-dired-source"
class "helm-source-sync"
"helm-source" <|-- "helm-source-sync"
class "helm-source"
class "helm-type-file"
"helm-source" <|-- "helm-type-file"
class "helm-source"
class "helm-files-dired-source" {
	__ some interesting slots __
	candidates
	match-dynamic
	match-strict
	migemo
}
note right of "helm-files-dired-source"
	**helm-files-dired-source**
end note
@enduml
